### ISSUE TITLE
open() gets clobbered by importing *

### ISSUE THREAD

**Issue by eah13** [trinketapp/processing.sk#20]
After importing * from processing, open() throws a NotImplemented error.

http://elliott-dev.trinket.io/python/ea99deda0a

Am I right in thinking this comes from here?

https://github.com/trinketapp/processing.sk/blob/acbfbfb2dacbc1422e3259e00c07938348e66396/src/files.js#L14

Might be worth a check to see if any other Python built ins or keywords are affected like this.  Discovered this in a production trinket that is used to visualize a csv

**Comment by albertjan** [comment]
oops 😁

**Comment by albertjan** [comment]
https://github.com/trinketapp/processing.sk/releases/tag/0.0.4
