### ISSUE TITLE
loadImage optional file type arg bug

### ISSUE THREAD

**Issue by eah13** [trinketapp/processing.sk#30]
Adding the optional filetype arg to loadImage throws an external error.

e.g. `loadImage("somepng", "png")`

Example from the docs:
https://trinket.io/python/d92b3a3994

**Comment by albertjan** [comment]
http://processingjs.org/reference/loadImage_/ 

Good catch this is a difference between processing js and processing py, and a bug in the `makeFunc` util because that should have thrown an error along the lines of too many args.
